from migen.build.generic_platform import *
from migen.build.lattice import LatticePlatform


_io = [
    ("clk25", 0, Pins("K9"), IOStandard("LVCMOS33")),
    ("user_led", 0, Pins("M2"), IOStandard("LVCMOS25")),
    ("user_led", 1, Pins("M3"), IOStandard("LVCMOS25")),
    ("user_led", 2, Pins("N3"), IOStandard("LVCMOS25")),
    ("user_led", 3, Pins("N2"), IOStandard("LVCMOS25")),
    ("user_led", 4, Pins("M6"), IOStandard("LVCMOS25")),
    ("user_led", 5, Pins("L6"), IOStandard("LVCMOS25")),
    ("user_led", 6, Pins("L7"), IOStandard("LVCMOS25")),
    ("user_led", 7, Pins("K5"), IOStandard("LVCMOS25")),
    ("user_led", 8, Pins("F1"), IOStandard("LVCMOS25")),  # RED

    ("test_point", 0, Pins("P1"), IOStandard("LVCMOS25")),
    ("test_point", 1, Pins("M5"), IOStandard("LVCMOS25")),
    ("test_point", 2, Pins("P2"), IOStandard("LVCMOS25")),
    ("test_point", 3, Pins("N4"), IOStandard("LVCMOS25")),
    ("test_point", 4, Pins("R1"), IOStandard("LVCMOS25")),

    ("hw_rev", 0, Pins("R6 R16 T15 T13 D8"), IOStandard("LVCMOS33")),
    ("sw", 0, Pins("K15 B8"), IOStandard("LVCMOS33")),
    ("cbsel", 0, Pins("K11 P13"), IOStandard("LVCMOS33")),

    ("i2c", 0,
        Subsignal("scl", Pins("M15")),
        Subsignal("sda", Pins("J11")),
        IOStandard("LVCMOS33"),
    ),
    ("i2c", 1,
        Subsignal("scl", Pins("R4")),
        Subsignal("sda", Pins("M7")),
        IOStandard("LVCMOS33"),
    ),

    ("spiflash", 0,
        Subsignal("cs_n", Pins("R12")),
        Subsignal("sck", Pins("R11")),
        Subsignal("mosi", Pins("P12")),
        Subsignal("miso", Pins("P11")),
        IOStandard("LVCMOS33"),
    ),

    # FIXME: yosys/nextpnr get confused if these are not broken up
    ("eem0_n", 0, Pins("J5")),
    ("eem0_p", 0, Pins("G1")),
    ("eem0_n", 1, Pins("K4")),
    ("eem0_p", 1, Pins("M1")),
    ("eem0_n", 2, Pins("K1")),
    ("eem0_p", 2, Pins("K3")),
    ("eem0_n", 3, Pins("J4")),
    ("eem0_p", 3, Pins("H2")),
    ("eem0_n", 4, Pins("H4")),
    ("eem0_p", 4, Pins("G2")),
    ("eem0_n", 5, Pins("G4")),
    ("eem0_p", 5, Pins("E3")),
    ("eem0_n", 6, Pins("F4")),
    ("eem0_p", 6, Pins("D2")),
    ("eem0_n", 7, Pins("E4")),
    ("eem0_p", 7, Pins("B2")),
    ("eem1_n", 0, Pins("J3")),
    ("eem1_p", 0, Pins("H1")),
    ("eem1_n", 1, Pins("L4")),
    ("eem1_p", 1, Pins("L1")),
    ("eem1_n", 2, Pins("J2")),
    ("eem1_p", 2, Pins("J1")),
    ("eem1_n", 3, Pins("H3")),
    ("eem1_p", 3, Pins("F2")),
    ("eem1_n", 4, Pins("H5")),
    ("eem1_p", 4, Pins("E2")),
    ("eem1_n", 5, Pins("G5")),
    ("eem1_p", 5, Pins("D1")),
    ("eem1_n", 6, Pins("C1")),
    ("eem1_p", 6, Pins("C2")),
    ("eem1_n", 7, Pins("F5")),
    ("eem1_p", 7, Pins("B1")),

    ("dac_clr_n", 4, Pins("A7"), IOStandard("LVCMOS33")),

    ("dac", 0,
        Subsignal("clk", Pins("C3")),
        Subsignal("ldacn", Pins("D4")),
        Subsignal("nss", Pins("E5")),
        Subsignal("sdi", Pins("D3")),
        IOStandard("LVCMOS33"),
    ), ("dac", 1,
        Subsignal("clk", Pins("B3")),
        Subsignal("ldacn", Pins("A1")),
        Subsignal("nss", Pins("C5")),
        Subsignal("sdi", Pins("C4")),
        IOStandard("LVCMOS33"),
    ), ("dac", 2,
        Subsignal("clk", Pins("D5")),
        Subsignal("ldacn", Pins("B5")),
        Subsignal("nss", Pins("E6")),
        Subsignal("sdi", Pins("A2")),
        IOStandard("LVCMOS33"),
    ), ("dac", 3,
        Subsignal("clk", Pins("A5")),
        Subsignal("ldacn", Pins("D7")),
        Subsignal("nss", Pins("A6")),
        Subsignal("sdi", Pins("D6")),
        IOStandard("LVCMOS33"),
    ), ("dac", 4,
        Subsignal("clk", Pins("C6")),
        Subsignal("ldacn", Pins("B7")),
        Subsignal("nss", Pins("C7")),
        Subsignal("sdi", Pins("B6")),
        IOStandard("LVCMOS33"),
    ), ("dac", 5,
        Subsignal("clk", Pins("B9")),
        Subsignal("ldacn", Pins("C8")),
        Subsignal("nss", Pins("F9")),
        Subsignal("sdi", Pins("F7")),
        IOStandard("LVCMOS33"),
    ), ("dac", 6,
        Subsignal("clk", Pins("D9")),
        Subsignal("ldacn", Pins("C9")),
        Subsignal("nss", Pins("D10")),
        Subsignal("sdi", Pins("E9")),
        IOStandard("LVCMOS33"),
    ), ("dac", 7,
        Subsignal("clk", Pins("A11")),
        Subsignal("ldacn", Pins("C10")),
        Subsignal("nss", Pins("B11")),
        Subsignal("sdi", Pins("A10")),
        IOStandard("LVCMOS33"),
    ), ("dac", 8,
        Subsignal("clk", Pins("R3")),
        Subsignal("ldacn", Pins("N5")),
        Subsignal("nss", Pins("T2")),
        Subsignal("sdi", Pins("P5")),
        IOStandard("LVCMOS33"),
    ), ("dac", 9,
         Subsignal("clk", Pins("B10")),
         Subsignal("ldacn", Pins("D11")),
         Subsignal("nss", Pins("C11")),
         Subsignal("sdi", Pins("B12")),
        IOStandard("LVCMOS33"),
    ), ("dac", 10,
         Subsignal("clk", Pins("E10")),
         Subsignal("ldacn", Pins("A15")),
         Subsignal("nss", Pins("A16")),
         Subsignal("sdi", Pins("B13")),
        IOStandard("LVCMOS33"),
    ), ("dac", 11,
         Subsignal("clk", Pins("P7")),
         Subsignal("ldacn", Pins("L9")),
         Subsignal("nss", Pins("T7")),
         Subsignal("sdi", Pins("T8")),
        IOStandard("LVCMOS33"),
    ), ("dac", 12,
         Subsignal("clk", Pins("B15")),
         Subsignal("ldacn", Pins("E13")),
         Subsignal("nss", Pins("B16")),
         Subsignal("sdi", Pins("C14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 13,
         Subsignal("clk", Pins("H11")),
         Subsignal("ldacn", Pins("J16")),
         Subsignal("nss", Pins("J13")),
         Subsignal("sdi", Pins("H13")),
        IOStandard("LVCMOS33"),
    ), ("dac", 14,
         Subsignal("clk", Pins("R9")),
         Subsignal("ldacn", Pins("N9")),
         Subsignal("nss", Pins("T9")),
         Subsignal("sdi", Pins("M9")),
        IOStandard("LVCMOS33"),
    ), ("dac", 15,
         Subsignal("clk", Pins("E11")),
         Subsignal("ldacn", Pins("B14")),
         Subsignal("nss", Pins("D13")),
         Subsignal("sdi", Pins("C12")),
        IOStandard("LVCMOS33"),
    ), ("dac", 16,
         Subsignal("clk", Pins("H12")),
         Subsignal("ldacn", Pins("H14")),
         Subsignal("nss", Pins("H16")),
         Subsignal("sdi", Pins("G16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 17,
         Subsignal("clk", Pins("M11")),
         Subsignal("ldacn", Pins("T10")),
         Subsignal("nss", Pins("T11")),
         Subsignal("sdi", Pins("T14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 18,
         Subsignal("clk", Pins("F12")),
         Subsignal("ldacn", Pins("G12")),
         Subsignal("nss", Pins("D16")),
         Subsignal("sdi", Pins("F14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 19,
         Subsignal("clk", Pins("J14")),
         Subsignal("ldacn", Pins("J15")),
         Subsignal("nss", Pins("K14")),
         Subsignal("sdi", Pins("K16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 20,
         Subsignal("clk", Pins("P15")),
         Subsignal("ldacn", Pins("R14")),
         Subsignal("nss", Pins("R15")),
         Subsignal("sdi", Pins("P14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 21,
         Subsignal("clk", Pins("F13")),
         Subsignal("ldacn", Pins("F11")),
         Subsignal("nss", Pins("D15")),
         Subsignal("sdi", Pins("C16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 22,
         Subsignal("clk", Pins("L12")),
         Subsignal("ldacn", Pins("M13")),
         Subsignal("nss", Pins("P16")),
         Subsignal("sdi", Pins("M14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 23,
         Subsignal("clk", Pins("N10")),
         Subsignal("ldacn", Pins("R10")),
         Subsignal("nss", Pins("L10")),
         Subsignal("sdi", Pins("P10")),
        IOStandard("LVCMOS33"),
    ), ("dac", 24,
         Subsignal("clk", Pins("G11")),
         Subsignal("ldacn", Pins("G10")),
         Subsignal("nss", Pins("G15")),
         Subsignal("sdi", Pins("F16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 25,
         Subsignal("clk", Pins("K13")),
         Subsignal("ldacn", Pins("J10")),
         Subsignal("nss", Pins("M16")),
         Subsignal("sdi", Pins("L16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 26,
         Subsignal("clk", Pins("T6")),
         Subsignal("ldacn", Pins("M8")),
         Subsignal("nss", Pins("T5")),
         Subsignal("sdi", Pins("P8")),
        IOStandard("LVCMOS33"),
    ), ("dac", 27,
         Subsignal("clk", Pins("G13")),
         Subsignal("ldacn", Pins("G14")),
         Subsignal("nss", Pins("F15")),
         Subsignal("sdi", Pins("E16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 28,
         Subsignal("clk", Pins("K12")),
         Subsignal("ldacn", Pins("L13")),
         Subsignal("nss", Pins("N16")),
         Subsignal("sdi", Pins("L14")),
        IOStandard("LVCMOS33"),
    ), ("dac", 29,
         Subsignal("clk", Pins("P6")),
         Subsignal("ldacn", Pins("R5")),
         Subsignal("nss", Pins("T3")),
         Subsignal("sdi", Pins("N7")),
        IOStandard("LVCMOS33"),
    ), ("dac", 30,
         Subsignal("clk", Pins("M12")),
         Subsignal("ldacn", Pins("N12")),
         Subsignal("nss", Pins("L11")),
         Subsignal("sdi", Pins("T16")),
        IOStandard("LVCMOS33"),
    ), ("dac", 31,
         Subsignal("clk", Pins("R2")),
         Subsignal("ldacn", Pins("N6")),
         Subsignal("nss", Pins("T1")),
         Subsignal("sdi", Pins("P4")),
        IOStandard("LVCMOS33"),
    ),
]


class Platform(LatticePlatform):
    default_clk_name = "clk25"
    default_clk_period = 40.

    def __init__(self):
        LatticePlatform.__init__(self, "ice40-hx8k-ct256", _io,
                                 toolchain="icestorm")
